version: '2'
services:
  vmware_exporter:
    # Using the latest tag, but you can use vers(v0.9.5 for example
    image: localhost/pryorda/vmware_exporter:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "9272:9272"
    volumes:
      - ./config.yml:/config.yml:ro
    restart: always
    #FOR DEBUG UNCOMMENT NEXT LINE
    command: ["-l","DEBUG", "-c" , "/config.yml"]
